// <auto-generated />
using System;
using DeveSpotnet.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeveSpotnet.Migrations.Postgres.Migrations
{
    [DbContext(typeof(DeveSpotnetDbContext))]
    [Migration("20250317190836_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeveSpotnet.Db.DbModels.DbSpotHeader", b =>
                {
                    b.Property<int>("ArticleNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArticleNumber"));

                    b.Property<int>("Bytes")
                        .HasColumnType("integer");

                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<string>("Date")
                        .HasColumnType("text");

                    b.Property<string>("From")
                        .HasColumnType("text");

                    b.Property<int>("Lines")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("MessageID")
                        .HasColumnType("text");

                    b.Property<int?>("ParsedHeader_Category")
                        .HasColumnType("integer");

                    b.Property<int?>("ParsedHeader_FileSize")
                        .HasColumnType("integer");

                    b.Property<string>("ParsedHeader_Header")
                        .HasColumnType("text");

                    b.Property<string>("ParsedHeader_HeaderSign")
                        .HasColumnType("text");

                    b.Property<int?>("ParsedHeader_KeyId")
                        .HasColumnType("integer");

                    b.Property<string>("ParsedHeader_MessageId")
                        .HasColumnType("text");

                    b.Property<string>("ParsedHeader_Poster")
                        .HasColumnType("text");

                    b.Property<string>("ParsedHeader_SelfSignedPubKey")
                        .HasColumnType("text");

                    b.Property<string>("ParsedHeader_SpotterId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ParsedHeader_Stamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ParsedHeader_SubCatA")
                        .HasColumnType("text");

                    b.Property<string>("ParsedHeader_SubCatB")
                        .HasColumnType("text");

                    b.Property<string>("ParsedHeader_SubCatC")
                        .HasColumnType("text");

                    b.Property<string>("ParsedHeader_SubCatD")
                        .HasColumnType("text");

                    b.Property<string>("ParsedHeader_SubCatZ")
                        .HasColumnType("text");

                    b.Property<string>("ParsedHeader_Tag")
                        .HasColumnType("text");

                    b.Property<string>("ParsedHeader_Title")
                        .HasColumnType("text");

                    b.Property<string>("ParsedHeader_UserKey_Exponent")
                        .HasColumnType("text");

                    b.Property<string>("ParsedHeader_UserKey_Modulo")
                        .HasColumnType("text");

                    b.Property<string>("ParsedHeader_UserSignature")
                        .HasColumnType("text");

                    b.Property<bool>("ParsedHeader_Valid")
                        .HasColumnType("boolean");

                    b.Property<bool?>("ParsedHeader_Verified")
                        .HasColumnType("boolean");

                    b.Property<bool?>("ParsedHeader_WasSigned")
                        .HasColumnType("boolean");

                    b.Property<string>("ParsedHeader_XmlSignature")
                        .HasColumnType("text");

                    b.Property<string>("References")
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.HasKey("ArticleNumber");

                    b.ToTable("SpotHeaders");
                });
#pragma warning restore 612, 618
        }
    }
}
